version: 2
jobs:
  build:
    working_directory: ~/micropost
    docker:
      - image: circleci/php:7.2.4-apache-stretch-node-browsers
        environment:
          APP_ENV: test
          DATABASE_URL: mysql://root:root@127.0.0.1/micro-post
          MAILER_FORM: micro@micropost.com
          MAILER_URL: null://localhost
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_DATABASE: micro-post
    steps:
      - checkout
      - run: sudo docker-php-ext-install pdo_mysql
      - run: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run: sudo composer self-update
      - run: composer install -n --prefer-dist
      - run: php bin/console doctrine:migrations:migrate --env=test --no-interaction
  deploy:
    docker:
      - image: circleci/php:7.2.4-apache-stretch-node-browsers
    working_directory: ~/micropost
    steps:
      - checkout
      - run: composer install -n --prefer-dist
      - run: php bin/console cache:clear --env=prod --no-interaction
      - run: yarn install && yarn run encore production
      - run: ssh-keyscan -H 206.189.19.93 >> ~/.ssh/known_hosts
      - run: ssh -T $DROPLET_USER@$DROPLET_IP < bin/deploy/pre_deploy.sh
      - run: rsync -vzcrSLhp --exclude '.env' --delete ~/micropost/ $DROPLET_USER@$DROPLET_IP:/var/www/micropost_current
      - run: ssh -T $DROPLET_USER@$DROPLET_IP < bin/deploy/deploy.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master